apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: basic-deployment-role 
  namespace: blue
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods","secrets","configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
