apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-small
spec:
  hard:
      requests.cpu: "8"
      requests.memory: "32Gi"
      requests.storage: "32Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-medium
spec:
  hard:
      requests.cpu: "16"
      requests.memory: "64Gi"
      requests.storage: "64Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-large
spec:
  hard:
      requests.cpu: "32"
      requests.memory: "128Gi"
      requests.storage: "128Gi"


