version: '3.8'
configs:
    prometheus.yml:
      file: ./prometheus.yml

services:
    monitoring-prometheus:
        image: prom/prometheus:latest
        hostname: monitoring-prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'            
        #volumes:
        #- prometheus-metrics-data:/prometheus
        configs:
        - source: prometheus.yml
          target: /etc/prometheus/prometheus.yml
        deploy:
            restart_policy:
              condition: any
              delay: 5s
              max_attempts: 5
            labels:
              com.docker.lb.hosts: prom.apps.avinash.dockerps.io
              com.docker.lb.network: grafana-prometheus_monitoring-frontend
              com.docker.lb.port: 9090
