apiVersion: v1
kind: PersistentVolume
metadata:
  name: povol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: 172.31.4.25
    readOnly: false
